var items = [
	'Food',
	'Energy',
	'Water',
	'Animal embryos',
	'Ore',
	'Metal',
	'Electronics',
	'Robots',
	'Heavy plastics',
	'Hand weapons',
	'Medicines',
	'Nebula gas',
	'Chemical supplies',
	'Gem stones',
	'Liquor',
	'Hydrogen fuel',
	'Exotic matter',
	'Optical components',
	'Radioactive cells',
	'Droid modules',
	'Bio-waste',
	'Leech baby',
	'Nutrient clods',
	'Cybernetic X-993 Parts',
	'X-993 Repair-Drone',
	'Neural Stimulator',
	'Battleweapon Parts',
	'Slaves',
	'Drugs',
	'Package',
	'Faction package',
	'Explosives',
	'VIP',
	'Christmas Glitter',
	'Military Explosives',
	'Human intestines',
	'Skaari limbs',
	'Keldon brains',
	'Rashkir bones',
	'Exotic Crystal',
	'Blue Sapphire jewels',
	'Ruby jewels',
	'Golden Beryl jewels',
	'Stim Chip',
	'Neural Tissue',
	'Capri Stim',
	'Crimson Stim',
	'Amber Stim'
];